apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csr-create-get
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csr-create-get
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: spire-agent

